export const dailyData = [
  {
    id: 1,
    name: 'Registered',
    value: 100,
    img: require('../../assets/icons/registered.png'),
  },
  {
    id: 2,
    name: 'Recommended',
    value: 200,
    img: require('../../assets/icons/recommended.png'),
  },
  {
    id: 3,
    name: 'Policy Sold',
    value: 85,
    img: require('../../assets/icons/soldPolicy.png'),
  },
  {
    id: 4,
    name: 'Payment Pending',
    value: 25,
    img: require('../../assets/icons/pendingPayment.png'),
  },
  {
    id: 5,
    name: 'Regular Customer',
    value: 72,
    img: require('../../assets/icons/RegularCustomer.png'),
  },
  {
    id: 6,
    name: 'Premium Due',
    value: 10,
    img: require('../../assets/icons/premiumDue.png'),
  },
  {
    id: 7,
    name: 'Conversion',
    value: 25,
    img: require('../../assets/icons/conversion.png'),
  },
  {
    id: 8,
    name: 'Field Force Active',
    value: 12,
    img: require('../../assets/icons/activeForce.png'),
  },
  {
    id: 9,
    name: 'Inactive Customer',
    value: 55,
    img: require('../../assets/icons/inactiveCustomer.png'),
  },
]
export const weeklyData = [
  {
    id: 1,
    name: 'Registered',
    value: 200,
    img: require('../../assets/icons/registered.png'),
  },
  {
    id: 2,
    name: 'Recommended',
    value: 250,
    img: require('../../assets/icons/recommended.png'),
  },
  {
    id: 3,
    name: 'Policy Sold',
    value: 70,
    img: require('../../assets/icons/soldPolicy.png'),
  },
  {
    id: 4,
    name: 'Payment Pending',
    value: 30,
    img: require('../../assets/icons/pendingPayment.png'),
  },
  {
    id: 5,
    name: 'Regular Customer',
    value: 70,
    img: require('../../assets/icons/RegularCustomer.png'),
  },
  {
    id: 6,
    name: 'Premium Due',
    value: 15,
    img: require('../../assets/icons/premiumDue.png'),
  },
  {
    id: 7,
    name: 'Conversion',
    value: 28,
    img: require('../../assets/icons/conversion.png'),
  },
  {
    id: 8,
    name: 'Field Force Active',
    value: 14,
    img: require('../../assets/icons/activeForce.png'),
  },
  {
    id: 9,
    name: 'Inactive Customer',
    value: 69,
    img: require('../../assets/icons/inactiveCustomer.png'),
  },
]
export const monthlyData = [
  {
    id: 1,
    name: 'Registered',
    value: 340,
    img: require('../../assets/icons/registered.png'),
  },
  {
    id: 2,
    name: 'Recommended',
    value: 300,
    img: require('../../assets/icons/recommended.png'),
  },
  {
    id: 3,
    name: 'Policy Sold',
    value: 100,
    img: require('../../assets/icons/soldPolicy.png'),
  },
  {
    id: 4,
    name: 'Payment Pending',
    value: 50,
    img: require('../../assets/icons/pendingPayment.png'),
  },
  {
    id: 5,
    name: 'Regular Customer',
    value: 85,
    img: require('../../assets/icons/RegularCustomer.png'),
  },
  {
    id: 6,
    name: 'Premium Due',
    value: 20,
    img: require('../../assets/icons/premiumDue.png'),
  },
  {
    id: 7,
    name: 'Conversion',
    value: 35,
    img: require('../../assets/icons/conversion.png'),
  },
  {
    id: 8,
    name: 'Field Force Active',
    value: 15,
    img: require('../../assets/icons/activeForce.png'),
  },
  {
    id: 9,
    name: 'Inactive Customer',
    value: 85,
    img: require('../../assets/icons/inactiveCustomer.png'),
  },
]
export const totalData = [
  {
    id: 1,
    name: 'Registered Customer',
    value: 340,
    img: require('../../assets/icons/registered.png'),
  },
  {
    id: 2,
    name: 'Policy Recommended',
    value: 300,
    img: require('../../assets/icons/recommended.png'),
  },
  {
    id: 3,
    name: 'Policy Sold',
    value: 100,
    img: require('../../assets/icons/soldPolicy.png'),
  },
  {
    id: 4,
    name: 'Payment Pending',
    value: 50,
    img: require('../../assets/icons/pendingPayment.png'),
  },
  {
    id: 5,
    name: 'Draft Policy',
    value: 50,
    img: require('../../assets/icons/pendingPayment.png'),
  },
  {
    id: 6,
    name: 'Regular Customer',
    value: 85,
    img: require('../../assets/icons/RegularCustomer.png'),
  },
  {
    id: 7,
    name: 'Inactive Customer',
    value: 20,
    img: require('../../assets/icons/premiumDue.png'),
  },
  {
    id: 8,
    name: 'Premium Due',
    value: 35,
    img: require('../../assets/icons/conversion.png'),
  },
  {
    id: 9,
    name: 'Conversion',
    value: 15,
    img: require('../../assets/icons/activeForce.png'),
  },
  {
    id: 10,
    name: 'Agent Activity Status',
    value: 85,
    img: require('../../assets/icons/inactiveCustomer.png'),
  },
]
// service
export const service = [
  {
    id: 1,
    name: 'Support',
    img: require('../../assets/icons/support.png'),
  },
  {
    id: 2,
    name: 'Quote',
    img: require('../../assets/icons/quote.png'),
  },
  {
    id: 3,
    name: 'Claim ',
    img: require('../../assets/icons/claim.png'),
  },
  {
    id: 4,
    name: 'Compare',
    img: require('../../assets/icons/compare.png'),
  },
]
// testimonials
export const testimonials = [
  {
    id: '01',
    name: 'Ema Watson',
    role: 'goforEma_Watson',
    message:
      '“Lorem ipsum dolor sit amet, consectetur adipiscing elit. @Waadaa.Insure. Mattis vehicula nunc leo vel est, magna nisl. Mattis magnis sit.Lorem ipsum dolor sit amet, consectetur ”',
    image: require('../../assets/user.png'),
  },
  {
    id: '02',
    name: 'Ema Watson',
    role: 'goforEma_Watson',
    message:
      '“Lorem ipsum dolor sit amet, consectetur adipiscing elit. @Waadaa.Insure. Mattis vehicula nunc leo vel est, magna nisl. Mattis magnis sit.Lorem ipsum dolor sit amet, consectetur ”',
    image: require('../../assets/user.png'),
  },
  {
    id: '03',
    name: 'Ema Watson',
    role: 'goforEma_Watson',
    message:
      '“Lorem ipsum dolor sit amet, consectetur adipiscing elit. @Waadaa.Insure. Mattis vehicula nunc leo vel est, magna nisl. Mattis magnis sit.Lorem ipsum dolor sit amet, consectetur ”',
    image: require('../../assets/user.png'),
  },
  {
    id: '04',
    name: 'Ema Watson',
    role: 'goforEma_Watson',
    message:
      '“Lorem ipsum dolor sit amet, consectetur adipiscing elit. @Waadaa.Insure. Mattis vehicula nunc leo vel est, magna nisl. Mattis magnis sit.Lorem ipsum dolor sit amet, consectetur ”',
    image: require('../../assets/user.png'),
  },
  {
    id: '05',
    name: 'Ema Watson',
    role: 'goforEma_Watson',
    message:
      '“Lorem ipsum dolor sit amet, consectetur adipiscing elit. @Waadaa.Insure. Mattis vehicula nunc leo vel est, magna nisl. Mattis magnis sit.Lorem ipsum dolor sit amet, consectetur ”',
    image: require('../../assets/user.png'),
  },
  {
    id: '06',
    name: 'Ema Watson',
    role: 'goforEma_Watson',
    message:
      '“Lorem ipsum dolor sit amet, consectetur adipiscing elit. @Waadaa.Insure. Mattis vehicula nunc leo vel est, magna nisl. Mattis magnis sit.Lorem ipsum dolor sit amet, consectetur ”',
    image: require('../../assets/user.png'),
  },
]
//  popularInsurance
export const popularInsurance = [
  {
    id: 1,
    category: 'Life Insurance',
    title: 'Shanti-Amra Sobai',
    image: require('../../assets/images/popularInImage.png'),
    coverage: 100000,
    term: 5,
    members: 'Self',
    premium: 540,
    status: 'NEW',
  },
  {
    id: 2,
    title: 'Shanti-Amra Sobai',
    image: require('../../assets/images/popularInImage.png'),
    coverage: 100000,
    term: 5,
    members: 'Self',
    premium: 540,
    status: 'NEW',
  },
  {
    id: 3,
    title: 'Shanti-Amra Sobai',
    image: require('../../assets/images/popularInImage.png'),
    coverage: 100000,
    term: 5,
    members: 'Self',
    premium: 540,
    status: 'NEW',
  },
  {
    id: 4,
    title: 'Shanti-Amra Sobai',
    image: require('../../assets/images/popularInImage.png'),
    coverage: 100000,
    term: 5,
    members: 'Self',
    premium: 540,
    status: 'NEW',
  },
  {
    id: 5,
    title: 'Shanti-Amra Sobai',
    image: require('../../assets/images/popularInImage.png'),
    coverage: 100000,
    term: 5,
    members: 'Self',
    premium: 540,
    status: 'NEW',
  },
  {
    id: 6,
    title: 'Shanti-Amra Sobai',
    image: require('../../assets/images/popularInImage.png'),
    coverage: 100000,
    term: 5,
    members: 'Self',
    premium: 540,
    status: 'NEW',
  },
  {
    id: 7,
    title: 'Shanti-Amra Sobai',
    image: require('../../assets/images/popularInImage.png'),
    coverage: 100000,
    term: 5,
    members: 'Self',
    premium: 540,
    status: 'NEW',
  },
  {
    id: 8,
    title: 'Shanti-Amra Sobai',
    image: require('../../assets/images/popularInImage.png'),
    coverage: 100000,
    term: 5,
    members: 'Self',
    premium: 540,
    status: 'NEW',
  },
]

export const popularInsuranceB2B = [
  {
    id: 1,
    title: 'Nishchinto-Amra Sobai',
    image: require('../../assets/images/popularInImage.png'),
    coverage: 80000,
    term: 10,
    members: 'Self',
    premium: 640,
    status: 'NEW',
  },
  {
    id: 2,
    title: 'Nishchinto-Amra Sobai',
    image: require('../../assets/images/popularInImage.png'),
    coverage: 100000,
    term: 5,
    members: 'Self',
    premium: 540,
    status: 'NEW',
  },
  {
    id: 3,
    title: 'Nishchinto-Amra Sobai',
    image: require('../../assets/images/popularInImage.png'),
    coverage: 100000,
    term: 5,
    members: 'Self',
    premium: 540,
    status: 'NEW',
  },
  {
    id: 4,
    title: 'Nishchinto-Amra Sobai',
    image: require('../../assets/images/popularInImage.png'),
    coverage: 100000,
    term: 5,
    members: 'Self',
    premium: 540,
    status: 'NEW',
  },
  {
    id: 5,
    title: 'Nishchinto-Amra Sobai',
    image: require('../../assets/images/popularInImage.png'),
    coverage: 100000,
    term: 5,
    members: 'Self',
    premium: 540,
    status: 'NEW',
  },
  {
    id: 6,
    title: 'Nishchinto-Amra Sobai',
    image: require('../../assets/images/popularInImage.png'),
    coverage: 100000,
    term: 5,
    members: 'Self',
    premium: 540,
    status: 'NEW',
  },
  {
    id: 7,
    title: 'Nishchinto-Amra Sobai',
    image: require('../../assets/images/popularInImage.png'),
    coverage: 100000,
    term: 5,
    members: 'Self',
    premium: 540,
    status: 'NEW',
  },
  {
    id: 8,
    title: 'Nishchinto-Amra Sobai',
    image: require('../../assets/images/popularInImage.png'),
    coverage: 100000,
    term: 5,
    members: 'Self',
    premium: 540,
    status: 'NEW',
  },
]
export const userInfo = [
  {
    id: 'HSDKJ54AS23509',
    name: 'Faisal Mahmud',
    email: 'mahmudrifat200@gmail.com',
    password: 'abc123',
    number: '01765021520',
    image: require('../../assets/images/popularInImage.png'),
    coverage: 100000,
    term: 5,
    members: 'Self',
    premium: 540,
    status: 'NEW',
  },
  {
    id: 'HSDKJ54AS23508',
    name: 'Farhad Mahmud',
    email: 'farhadmahmud@gmail.com',
    password: '123abc',
    number: '01710951562',
    image: require('../../assets/images/popularInImage.png'),
    coverage: 100000,
    term: 5,
    members: 'Self',
    premium: 540,
    status: 'NEW',
  },
  {
    id: 3,
    name: 'Shanti-Amra Sobai',
    image: require('../../assets/images/popularInImage.png'),
    coverage: 100000,
    term: 5,
    members: 'Self',
    premium: 540,
    status: 'NEW',
  },
  {
    id: 4,
    name: 'Shanti-Amra Sobai',
    image: require('../../assets/images/popularInImage.png'),
    coverage: 100000,
    term: 5,
    members: 'Self',
    premium: 540,
    status: 'NEW',
  },
  {
    id: 5,
    name: 'Shanti-Amra Sobai',
    image: require('../../assets/images/popularInImage.png'),
    coverage: 100000,
    term: 5,
    members: 'Self',
    premium: 540,
    status: 'NEW',
  },
  {
    id: 6,
    name: 'Shanti-Amra Sobai',
    image: require('../../assets/images/popularInImage.png'),
    coverage: 100000,
    term: 5,
    members: 'Self',
    premium: 540,
    status: 'NEW',
  },
  {
    id: 7,
    name: 'Shanti-Amra Sobai',
    image: require('../../assets/images/popularInImage.png'),
    coverage: 100000,
    term: 5,
    members: 'Self',
    premium: 540,
    status: 'NEW',
  },
  {
    id: 8,
    name: 'Shanti-Amra Sobai',
    image: require('../../assets/images/popularInImage.png'),
    coverage: 100000,
    term: 5,
    members: 'Self',
    premium: 540,
    status: 'NEW',
  },
]
export const zone = [
  {
    id: 1,
    title: 'Uttara',
  },
  {
    id: 1,
    title: 'Mirpur',
  },
  {
    id: 1,
    title: 'Paltan',
  },
  {
    id: 1,
    title: 'Motijhil',
  },
  {
    id: 1,
    title: 'Gulshan',
  },
]
export const categoriesData = [
  {
    id: 1,
    title: 'Life',
    name: 'Life Insurance',
    count: 84,
    image: require('../../assets/life-insurance.png'),
    policyList: [
      {
        id: 1,
        catId: 1,
        businessCat: 'B2C',
        category: 'Life Insurance',
        name: 'Shanti-Amra Sobai',
        image: require('../../assets/images/popularInImage.png'),
        total_coverage_amount: 100000,
        term: 5,
        duration: 365,
        durationType: 'Days',
        number_of_insured_as_text: 'Self',
        premium_amount: 540,
        status: 'NEW',
        slug: 'p-1',
        policy: 'No Refund Premium Maturity',
        paymentMethod: 'Yearly',
      },
      {
        id: 2,
        catId: 2,
        businessCat: 'B2C',
        category: 'Life Insurance',
        name: 'Shanti-Amra Sobai',
        image: require('../../assets/images/popularInImage.png'),
        total_coverage_amount: 100000,
        term: 5,
        duration: 365,
        durationType: 'Days',
        number_of_insured_as_text: 'Self',
        premium_amount: 540,
        status: 'NEW',
        slug: 'p-2',
        policy: 'Full Refund Premium Maturity',
        paymentMethod: 'Monthly',
      },
      {
        id: 3,
        catId: 1,
        businessCat: 'B2C',
        category: 'Life Insurance',
        name: 'Shanti-Amra Sobai',
        image: require('../../assets/images/popularInImage.png'),
        total_coverage_amount: 100000,
        term: 5,
        duration: 365,
        durationType: 'Days',
        number_of_insured_as_text: 'Self',
        premium_amount: 540,
        status: 'NEW',
        slug: 'p-3',
        policy: 'No refund premium_amount Maturity',
        paymentMethod: 'Yearly',
      },
      {
        id: 4,
        catId: 1,
        businessCat: 'B2C',
        category: 'Life Insurance',
        name: 'Shanti-Amra Sobai',
        image: require('../../assets/images/popularInImage.png'),
        total_coverage_amount: 100000,
        term: 5,
        duration: 365,
        durationType: 'Days',
        number_of_insured_as_text: 'Self',
        premium_amount: 540,
        status: 'NEW',
        slug: 'p-4',
        policy: 'Full refund premium_amount Maturity',
        paymentMethod: 'Monthly',
      },
      {
        id: 5,
        catId: 1,
        businessCat: 'B2C',
        category: 'Life Insurance',
        name: 'Shanti-Amra Sobai',
        image: require('../../assets/images/popularInImage.png'),
        total_coverage_amount: 100000,
        term: 5,
        duration: 365,
        durationType: 'Days',
        number_of_insured_as_text: 'Self',
        premium_amount: 540,
        status: 'NEW',
        slug: 'p-5',
        paymentMethod: 'Yearly',
        policy: 'No refund premium_amount Maturity',
      },
      {
        id: 6,
        catId: 1,
        businessCat: 'B2C',
        category: 'Life Insurance',
        name: 'Shanti-Amra Sobai',
        image: require('../../assets/images/popularInImage.png'),
        total_coverage_amount: 100000,
        term: 5,
        duration: 365,
        durationType: 'Days',
        number_of_insured_as_text: 'Self',
        premium_amount: 540,
        status: 'NEW',
        slug: 'p-6',
        paymentMethod: 'Yearly',
        policy: 'Full refund premium_amount Maturity',
      },
      {
        id: 7,
        catId: 1,
        businessCat: 'B2C',
        category: 'Life Insurance',
        name: 'Shanti-Amra Sobai',
        image: require('../../assets/images/popularInImage.png'),
        total_coverage_amount: 100000,
        term: 5,
        duration: 365,
        durationType: 'Days',
        number_of_insured_as_text: 'Self',
        premium_amount: 540,
        status: 'NEW',
        slug: 'p-7',
        paymentMethod: 'Monthly',
        policy: 'No refund premium_amount Maturity',
      },
      {
        id: 8,
        catId: 1,
        businessCat: 'B2C',
        category: 'Life Insurance',
        name: 'Shanti-Amra Last',
        image: require('../../assets/images/popularInImage.png'),
        total_coverage_amount: 100000,
        term: 5,
        duration: 365,
        durationType: 'Days',
        number_of_insured_as_text: 'Self',
        premium_amount: 540,
        status: 'NEW',
        slug: 'p-8',
        paymentMethod: 'Yearly',
        policy: 'Full refund premium_amount Maturity',
      },
    ],
    policyListB2B: [
      {
        id: 1,
        catId: 1,
        businessCat: 'B2B',
        category: 'Life Insurance',
        name: 'Shanti-Amra B2B',
        image: require('../../assets/images/popularInImage.png'),
        total_coverage_amount: 100000,
        term: 5,
        duration: 365,
        durationType: 'Days',
        number_of_insured_as_text: 'Self',
        premium_amount: 540,
        status: 'NEW',
        slug: 'p-9',
        paymentMethod: 'Yearly',
        policy: 'No refund premium_amount Maturity',
      },
      {
        id: 2,
        catId: 1,
        businessCat: 'B2B',
        category: 'Life Insurance',
        name: 'Shanti-Amra B2B',
        image: require('../../assets/images/popularInImage.png'),
        total_coverage_amount: 100000,
        term: 5,
        duration: 365,
        durationType: 'Days',
        number_of_insured_as_text: 'Self',
        premium_amount: 540,
        status: 'NEW',
        slug: 'p-10',
        paymentMethod: 'Monthly',
        policy: 'Full refund premium_amount Maturity',
      },
      {
        id: 3,
        catId: 1,
        businessCat: 'B2B',
        category: 'Life Insurance',
        name: 'Shanti-Amra B2B',
        image: require('../../assets/images/popularInImage.png'),
        total_coverage_amount: 100000,
        term: 5,
        duration: 365,
        durationType: 'Days',
        number_of_insured_as_text: 'Self',
        premium_amount: 540,
        status: 'NEW',
        slug: 'p-11',
        paymentMethod: 'Yearly',
        policy: 'No refund premium_amount Maturity',
      },
      {
        id: 4,
        catId: 1,
        businessCat: 'B2B',
        category: 'Life Insurance',
        name: 'Shanti-Amra B2B',
        image: require('../../assets/images/popularInImage.png'),
        total_coverage_amount: 100000,
        term: 5,
        duration: 365,
        durationType: 'Days',
        number_of_insured_as_text: 'Self',
        premium_amount: 540,
        status: 'NEW',
        slug: 'p-12',
        paymentMethod: 'Monthly',
        policy: 'Full refund premium_amount Maturity',
      },
      {
        id: 5,
        catId: 1,
        businessCat: 'B2B',
        category: 'Life Insurance',
        name: 'Shanti-Amra B2B',
        image: require('../../assets/images/popularInImage.png'),
        total_coverage_amount: 100000,
        term: 5,
        duration: 365,
        durationType: 'Days',
        number_of_insured_as_text: 'Self',
        premium_amount: 540,
        status: 'NEW',
        slug: 'p-13',
        paymentMethod: 'Yearly',
        policy: 'No refund premium_amount Maturity',
      },
      {
        id: 6,
        catId: 1,
        businessCat: 'B2B',
        category: 'Life Insurance',
        name: 'Shanti-Amra B2B',
        image: require('../../assets/images/popularInImage.png'),
        total_coverage_amount: 100000,
        term: 5,
        duration: 365,
        durationType: 'Days',
        number_of_insured_as_text: 'Self',
        premium_amount: 540,
        status: 'NEW',
        slug: 'p-14',
        paymentMethod: 'Monthly',
        policy: 'Full refund premium_amount Maturity',
      },
      {
        id: 7,
        catId: 1,
        businessCat: 'B2B',
        category: 'Life Insurance',
        name: 'Shanti-Amra B2B',
        image: require('../../assets/images/popularInImage.png'),
        total_coverage_amount: 100000,
        term: 5,
        duration: 365,
        durationType: 'Days',
        number_of_insured_as_text: 'Self',
        premium_amount: 540,
        status: 'NEW',
        slug: 'p-15',
        paymentMethod: 'Yearly',
        policy: 'No refund premium_amount Maturity',
      },
      {
        id: 8,
        catId: 1,
        businessCat: 'B2B',
        category: 'Life Insurance',
        name: 'Shanti-Amra Last',
        image: require('../../assets/images/popularInImage.png'),
        total_coverage_amount: 100000,
        term: 5,
        duration: 365,
        durationType: 'Days',
        number_of_insured_as_text: 'Self',
        premium_amount: 540,
        status: 'NEW',
        slug: 'p-16',
        paymentMethod: 'Monthly',
        policy: 'Full refund premium_amount Maturity',
      },
    ],
  },
  {
    id: 2,
    title: 'Health',
    name: 'Health Insurance',
    count: 56,
    image: require('../../assets/health-insurance.png'),
    policyList: [
      {
        id: 1,
        catId: 2,
        businessCat: 'B2C',
        businessCat: 'B2C',
        category: 'Health Insurance',
        title: 'Health-Amra Sobai',
        image: require('../../assets/images/popularInImage.png'),
        coverage: 100000,
        term: 5,
        members: 'Self',
        premium: 540,
        status: 'NEW',
      },
      {
        id: 2,
        catId: 2,
        businessCat: 'B2C',
        category: 'Health Insurance',
        title: 'Health-Amra Sobai',
        image: require('../../assets/images/popularInImage.png'),
        coverage: 100000,
        term: 5,
        members: 'Self',
        premium: 540,
        status: 'NEW',
      },
      {
        id: 3,
        catId: 2,
        businessCat: 'B2C',
        category: 'Health Insurance',
        title: 'Health-Amra Sobai',
        image: require('../../assets/images/popularInImage.png'),
        coverage: 100000,
        term: 5,
        members: 'Self',
        premium: 540,
        status: 'NEW',
      },
      {
        id: 4,
        catId: 2,
        businessCat: 'B2C',
        category: 'Health Insurance',
        title: 'Health-Amra Sobai',
        image: require('../../assets/images/popularInImage.png'),
        coverage: 100000,
        term: 5,
        members: 'Self',
        premium: 540,
        status: 'NEW',
      },
      {
        id: 5,
        catId: 2,
        businessCat: 'B2C',
        category: 'Health Insurance',
        title: 'Health-Amra Sobai',
        image: require('../../assets/images/popularInImage.png'),
        coverage: 100000,
        term: 5,
        members: 'Self',
        premium: 540,
        status: 'NEW',
      },
      {
        id: 6,
        catId: 2,
        businessCat: 'B2C',
        category: 'Health Insurance',
        title: 'Health-Amra Sobai',
        image: require('../../assets/images/popularInImage.png'),
        coverage: 100000,
        term: 5,
        members: 'Self',
        premium: 540,
        status: 'NEW',
      },
      {
        id: 7,
        catId: 2,
        businessCat: 'B2C',
        category: 'Health Insurance',
        title: 'Health-Amra Sobai',
        image: require('../../assets/images/popularInImage.png'),
        coverage: 100000,
        term: 5,
        members: 'Self',
        premium: 540,
        status: 'NEW',
      },
      {
        id: 8,
        catId: 2,
        businessCat: 'B2C',
        category: 'Health Insurance',
        title: 'Health-Amra Sobai',
        image: require('../../assets/images/popularInImage.png'),
        coverage: 100000,
        term: 5,
        members: 'Self',
        premium: 540,
        status: 'NEW',
      },
    ],
    policyListB2B: [
      {
        id: 1,
        catId: 2,
        businessCat: 'B2B',
        category: 'Health Insurance',
        title: 'Health-Amra B2B',
        image: require('../../assets/images/popularInImage.png'),
        coverage: 100000,
        term: 5,
        members: 'Self',
        premium: 540,
        status: 'NEW',
      },
      {
        id: 2,
        catId: 2,
        businessCat: 'B2B',
        category: 'Health Insurance',
        title: 'Health-Amra B2B',
        image: require('../../assets/images/popularInImage.png'),
        coverage: 100000,
        term: 5,
        members: 'Self',
        premium: 540,
        status: 'NEW',
      },
      {
        id: 3,
        catId: 2,
        businessCat: 'B2B',
        category: 'Health Insurance',
        title: 'Health-Amra B2B',
        image: require('../../assets/images/popularInImage.png'),
        coverage: 100000,
        term: 5,
        members: 'Self',
        premium: 540,
        status: 'NEW',
      },
      {
        id: 4,
        catId: 2,
        businessCat: 'B2B',
        category: 'Health Insurance',
        title: 'Health-Amra B2B',
        image: require('../../assets/images/popularInImage.png'),
        coverage: 100000,
        term: 5,
        members: 'Self',
        premium: 540,
        status: 'NEW',
      },
      {
        id: 5,
        catId: 2,
        businessCat: 'B2B',
        category: 'Health Insurance',
        title: 'Health-Amra B2B',
        image: require('../../assets/images/popularInImage.png'),
        coverage: 100000,
        term: 5,
        members: 'Self',
        premium: 540,
        status: 'NEW',
      },
      {
        id: 6,
        catId: 2,
        businessCat: 'B2B',
        category: 'Health Insurance',
        title: 'Health-Amra B2B',
        image: require('../../assets/images/popularInImage.png'),
        coverage: 100000,
        term: 5,
        members: 'Self',
        premium: 540,
        status: 'NEW',
      },
      {
        id: 7,
        catId: 2,
        businessCat: 'B2B',
        category: 'Health Insurance',
        title: 'Health-Amra B2B',
        image: require('../../assets/images/popularInImage.png'),
        coverage: 100000,
        term: 5,
        members: 'Self',
        premium: 540,
        status: 'NEW',
      },
      {
        id: 8,
        catId: 2,
        businessCat: 'B2B',
        category: 'Health Insurance',
        title: 'Health-Amra B2B',
        image: require('../../assets/images/popularInImage.png'),
        coverage: 100000,
        term: 5,
        members: 'Self',
        premium: 540,
        status: 'NEW',
      },
    ],
  },
  {
    id: 3,
    title: 'Travel',
    name: 'Travel Insurance',
    count: 34,
    image: require('../../assets/travel-insurance.png'),
  },
  {
    id: 5,
    title: 'Motor',
    name: 'Motor Insurance',
    count: 98,
    image: require('../../assets/motor-insurance.png'),
  },
  {
    id: 6,
    title: 'Device',
    name: 'Device Insurance',
    count: 23,
    image: require('../../assets/device-insurance.png'),
  },
]

// export const
